### ISSUE TITLE
Rewrite CodeEditor using state machines

### ISSUE THREAD

**Issue by dielduarte** [dielduarte/graphql-devtools#1]

**Comment by dielduarte** [comment]
So @StanleySathler, I've drafted some ideas that I think can guide us to finish the code editor

first here's the list of code editor features, in the version 1.0

- copy
- refetch 
- switch contexts (query or mutation, variables, headers)

**Copy**

<img width="777" alt="Screen Shot 2020-04-04 at 4 10 48 AM" src="https://user-images.githubusercontent.com/5679671/78421068-5a5df600-762b-11ea-941e-d3f0a5088f0c.png">
<img width="785" alt="Screen Shot 2020-04-04 at 4 10 57 AM" src="https://user-images.githubusercontent.com/5679671/78421071-5d58e680-762b-11ea-84f3-2e34553d86de.png">
<img width="781" alt="Screen Shot 2020-04-04 at 4 11 04 AM" src="https://user-images.githubusercontent.com/5679671/78421072-5df17d00-762b-11ea-9908-b412304d5726.png">

I think we don't need a loading state in this case, since the copy function is pretty fast, so I think doesn't worth the effort. after we've got to the success or error state, it should back to the idle state after some milliseconds defined (something like 500ms).


**Refetch**

<img width="802" alt="Screen Shot 2020-04-04 at 4 11 20 AM" src="https://user-images.githubusercontent.com/5679671/78421146-e2dc9680-762b-11ea-893b-14ce569447fc.png">
<img width="801" alt="Screen Shot 2020-04-04 at 4 11 28 AM" src="https://user-images.githubusercontent.com/5679671/78421151-e53ef080-762b-11ea-83cc-3e3e21c673d1.png">
<img width="815" alt="Screen Shot 2020-04-04 at 4 11 35 AM" src="https://user-images.githubusercontent.com/5679671/78421152-e5d78700-762b-11ea-90c6-b29491320099.png">

it should basically get all data we have query/mutation, variables and headers and send a new request. After the request completed it should back to the idle state.

 **switch contexts**

I thought tabs wouldn't be the best solution since we will have the query filters at the top and other stuff, so I came up with this idea:

<img width="731" alt="Screen Shot 2020-04-04 at 4 09 36 AM" src="https://user-images.githubusercontent.com/5679671/78421224-66968300-762c-11ea-81d1-e491cf8ddef7.png">

hovering options, I thought about just a slide effect showing the rest of the word:

<img width="728" alt="Screen Shot 2020-04-04 at 4 09 45 AM" src="https://user-images.githubusercontent.com/5679671/78421227-68f8dd00-762c-11ea-98e1-4ada0a38f40b.png">
<img width="671" alt="Screen Shot 2020-04-04 at 4 10 36 AM" src="https://user-images.githubusercontent.com/5679671/78421230-6ac2a080-762c-11ea-92c0-7003ec35638a.png">

in these examples above, let's suppose the user has selected variables, in the first example he was opening a query so the query goes to the options with its color (green):

<img width="735" alt="Screen Shot 2020-04-04 at 4 09 58 AM" src="https://user-images.githubusercontent.com/5679671/78421228-6a2a0a00-762c-11ea-900b-ca03432dea7c.png">

in the example below he was opening a mutation so the mutation goes to the options with its color (orange):

<img width="678" alt="Screen Shot 2020-04-04 at 4 10 17 AM" src="https://user-images.githubusercontent.com/5679671/78421229-6ac2a080-762c-11ea-8ce8-b9557fc4d38b.png">

I may show up with some state machine ideas tomorrow, let me know what do u think! 👊

**Comment by dielduarte** [comment]
here's a state machine draft for that, let me know what do you think.  in the code will need some DRY applied, but as I said, just a draft.

https://xstate.js.org/viz/?gist=c87dd4a0bd89e2bc91db2ad18403a4ab

**Comment by StanleySathler** [comment]
Thanks for the hard work preparing all these details, @dielduarte! :star2: 

Do you foresee any kind of situation that could lead to a failed "copy to the clipboard"?

**Comment by dielduarte** [comment]
@StanleySathler Honestly, I don't think this is gonna happen especially due to the simplicity of the copy helper function. 

you can either skip this state for a while or maybe involve the fn with a try-catch and treat any possible error as failed, both options I'm okay with!
