### ISSUE TITLE
Use `webpack-extension-reloader` to instantly update our Chrome extension on every change

### ISSUE THREAD

**Issue by StanleySathler** [dielduarte/graphql-devtools#20]
So far, developing the extension required a lot of manual work because whenever we made a new change, we had to go to `chrome://extensions` page to manually reload our extension.

However, there is a Webpack plugin called [`webpack-extension-reloader`](https://github.com/rubenspgcavalcante/webpack-extension-reloader) that creates a bridge between our Webpack and our Chrome (through a background script), updating our extension whenever a new change is applied.

We thought, initially, to mock the Chrome's `webRequest` API on the development environment (partially discussed in #14). However, mocking this interface could bring us some problems in the future. After some discussions and ideas, we decided to give the `webpack-extension-reloader` a change to see what happens.

**Comment by dielduarte** [comment]
this PR closes this issue: https://github.com/dielduarte/graphql-devtools/pull/21
