### ISSUE TITLE
check all colors and contrast 

### ISSUE THREAD

**Issue by dielduarte** [dielduarte/graphql-devtools#24]
Currently, our color palette is not so accessible, we want to fix it in order to launch the first version. this will impact all colors of the user interface, I believe.

it seems to be a good tool for testing contrasts: 
https://webaim.org/resources/contrastchecker/

here's our color palette right now:

<img width="598" alt="Screen Shot 2020-04-04 at 2 23 57 AM" src="https://user-images.githubusercontent.com/5679671/78419362-748fd800-761b-11ea-86cf-745c7d66a264.png">

the screen example:

<img width="725" alt="Screen Shot 2020-04-04 at 2 24 27 AM" src="https://user-images.githubusercontent.com/5679671/78419368-7f4a6d00-761b-11ea-8927-fca9b0f5feab.png">

and a good example of the problem we are facing:

![78394156-7a58cf80-75c1-11ea-817e-ab9d98da56c4](https://user-images.githubusercontent.com/5679671/78419386-94bf9700-761b-11ea-8a23-21c0253dcbef.png)

**Comment by dielduarte** [comment]
it was originally started being discussed here: https://github.com/dielduarte/graphql-devtools/pull/23

**Comment by brunopulis** [comment]
Hey @dielduarte I think the best tool of colour contrast is s Colour Contrast Analyzer of Paciello Group. 

Check it https://developer.paciellogroup.com/resources/contrastanalyser/

**Comment by dielduarte** [comment]
Thank you @brunopulis! It will be really helpful 😍
