### ISSUE TITLE
UI refactoring

### ISSUE THREAD

**Issue by dielduarte** [dielduarte/graphql-devtools#41]
Hey folks, I got busy with work these last two weeks and that's why I didn't any update here.

meanwhile, I friend of mine was reworking on how the final UI will look, and he did an AMAZING job!

I'd like to share the Figma link here so anyone can check it out.
https://www.figma.com/file/o7nb4VRer5YuwshqTBxBkF/Graphql-devtools?node-id=347%3A0

I'll be working on this refactoring, and probably will show up with a PR soon. I've other open source projects too, and new ideias to working on so after this redesign if you have any new ideas feel free to send a PR.

we still with plans for v2, adding the timeline and it will not be covered in this refactoring.

that said, thank you for all the hard work untill now!

cc @StanleySathler, @assuncaocharles

**Comment by StanleySathler** [comment]
Geez, the new design is completely **AWESOME!** :heart_eyes:
