### ISSUE TITLE
Empty messages and treatments

### ISSUE THREAD

**Issue by dielduarte** [dielduarte/graphql-devtools#8]

**Comment by dielduarte** [comment]
@StanleySathler how about these ideas treating empty states? 


<img width="716" alt="Screen Shot 2020-04-01 at 1 06 52 AM" src="https://user-images.githubusercontent.com/5679671/78098349-37c2a780-73b5-11ea-84c8-d063602b7f8f.png">
<img width="719" alt="Screen Shot 2020-04-01 at 12 58 52 AM" src="https://user-images.githubusercontent.com/5679671/78098353-398c6b00-73b5-11ea-8f26-a03f6596ab91.png">


let me know what do you think, they are available in the Figma project. Any suggestions are really welcome!

👊

**Comment by StanleySathler** [comment]
Oh, somehow I managed to lose these messages, @dielduarte. I've just seen it now while reviewing your PR. :joy: 

I definitely loved the designs. They're great!
